name: Send Email

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_EMAIL: ${{ secrets.EMAIL }}
          envkey_PASSWORD: ${{ secrets.PASSWORD }}
          envkey_TO: ${{ secrets.TO }}
          envkey_URL: "http://api.openweathermap.org"
          file_name: .env
          fail_on_empty: true

      - name: Send Email
        run: python main.py
